#!/bin/sh
set -e

if git diff --cached --name-only --diff-filter=ACMR | grep -q -E '\.(ts|json)$'; then
  git diff --cached --name-only -z --diff-filter=ACMR | grep -z -E '\.(ts|json)$' | xargs -0 pnpm biome ci
fi

pnpm run typecheck

if git diff --cached --name-only --diff-filter=ACMR | grep -q '\.ts$'; then
  git diff --cached --name-only -z --diff-filter=ACMR | grep -z '\.ts$' | xargs -0 pnpm vitest related --run
fi
