services:
    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        tty: true
        volumes:
            - .:/workspace
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        pids_limit: 200
