packages:
  - .

catalog:
  '@biomejs/biome': 2.3.5
  '@types/chrome': 0.1.31
  '@types/node': 24.10.1
  '@typescript/native-preview': 7.0.0-dev.20251123.1
  '@vitest/coverage-v8': 4.0.9
  esbuild: 0.27.0
  typescript: 5.9.3
  vitest: 4.0.9

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

linkWorkspacePackages: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - typescript
  - '@typescript/native-preview'

packageManagerStrictVersion: true

preferWorkspacePackages: true

resolutionMode: time-based

savePrefix: ''

strictDepBuilds: true

strictPeerDependencies: true
