name: Feature Request

description: Create a feature request to enhance the experience using Window Merger.

title: "[Feature Request] Replace with title"

labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Place a brief description in the title of this feature request.

        Thank you for taking the time to create this feature request.

  - type: textarea
    attributes:
      label: Feature Request Description
      description: Provide a clear and concise description of this feature request with any problems and solutions.
    validations:
      required: true
