name: Call CI
on: pull_request

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  call:
    name: CI
    permissions:
      contents: read # needed for reusable workflow
    uses: pHo9UBenaA/gh-action-templates/.github/workflows/pnpm-biome-ci.yml@d102bbd46f2dc4e0aa6822b4ec91216d0dea448b # master
