name: Call CI
on: pull_request

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  call:
    name: CI
    permissions:
      contents: read # needed for reusable workflow
    uses: pHo9UBenaA/gh-action-templates/.github/workflows/pnpm-biome-ci.yml@ac8266b50282c82e90ebb01ae2911625d0ca1246 # master
